GET http://localhost:4000/todo/all

###

POST http://localhost:4000/todo/new
Content-Type: application/json

{
    "text": "get the car"
}

###

DELETE http://localhost:4000/todo/delete/64bbdc85d535578cead6b8b4

###

PUT  http://localhost:4000/todo/complete/64bbdd9a6c85d76ed616c846